pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}



dependencyResolutionManagement {
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name='openRPGator'
include 'engine-core','engine-world','engine-map','engine-script','engine-network','engine-runtime','pak','renderer-api','renderer-desktop','dedicated-server','server-admin','map-editor','script-editor','desktop-client','android-client'
