def lwjglVersion = '3.3.3'
def lwjglNatives = providers.gradleProperty('lwjglNatives').orElse('natives-linux').get()

dependencies {
    api project(':renderer-api')
    implementation project(':pak')
    implementation "org.lwjgl:lwjgl:${lwjglVersion}"
    implementation "org.lwjgl:lwjgl-glfw:${lwjglVersion}"
    implementation "org.lwjgl:lwjgl-opengl:${lwjglVersion}"

    runtimeOnly "org.lwjgl:lwjgl:${lwjglVersion}:${lwjglNatives}"
    runtimeOnly "org.lwjgl:lwjgl-glfw:${lwjglVersion}:${lwjglNatives}"
    runtimeOnly "org.lwjgl:lwjgl-opengl:${lwjglVersion}:${lwjglNatives}"
}
