package rpg.engine.world;
import rpg.engine.core.ecs.*; import rpg.engine.core.component.*; import rpg.engine.core.math.*; import java.util.*;
public final class CollisionWorld {
 private final WorldRegistry registry; public CollisionWorld(WorldRegistry r){registry=r;}
 public boolean canOccupy(EntityId moving,WorldPosition p){var c=registry.get(moving,Collider.class);if(c.isEmpty())return true;for(var e:registry.entities()){if(e.equals(moving))continue;var oc=registry.get(e,Collider.class);var ot=registry.get(e,Transform.class);if(oc.isPresent()&&ot.isPresent()&&intersects(c.get(),p,oc.get(),ot.get().position()))return false;}return true;}
 public WorldPosition move(EntityId e,WorldPosition desired){var t=registry.get(e,Transform.class).orElseThrow();if(canOccupy(e,desired))return desired;var x=new WorldPosition(desired.x(),t.position().y(),desired.elevation());if(canOccupy(e,x))return x;var y=new WorldPosition(t.position().x(),desired.y(),desired.elevation());if(canOccupy(e,y))return y;return t.position();}
 public static boolean intersects(Collider a,WorldPosition ap,Collider b,WorldPosition bp){if(a instanceof CircleCollider ca&&b instanceof CircleCollider cb)return ap.xy().sub(bp.xy()).length()<=ca.radius()+cb.radius(); if(a instanceof BoxCollider ba&&b instanceof BoxCollider bb)return Math.abs(ap.x()-bp.x())<=ba.half().x()+bb.half().x()&&Math.abs(ap.y()-bp.y())<=ba.half().y()+bb.half().y(); return bounds(a,ap).intersects(bounds(b,bp));}
 private record Rect(double minX,double minY,double maxX,double maxY){boolean intersects(Rect r){return minX<=r.maxX&&maxX>=r.minX&&minY<=r.maxY&&maxY>=r.minY;}}
 private static Rect bounds(Collider c,WorldPosition p){if(c instanceof BoxCollider b)return new Rect(p.x()-b.half().x(),p.y()-b.half().y(),p.x()+b.half().x(),p.y()+b.half().y());if(c instanceof CircleCollider q)return new Rect(p.x()-q.radius(),p.y()-q.radius(),p.x()+q.radius(),p.y()+q.radius());var v=((PolygonCollider)c).vertices();double minx=Double.POSITIVE_INFINITY,miny=Double.POSITIVE_INFINITY,maxx=-minx,maxy=-miny;for(var x:v){minx=Math.min(minx,p.x()+x.x());maxx=Math.max(maxx,p.x()+x.x());miny=Math.min(miny,p.y()+x.y());maxy=Math.max(maxy,p.y()+x.y());}return new Rect(minx,miny,maxx,maxy);}
}
